apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: altinojunior
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-altinojunior