apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: altinojunior
spec:
  selector:
    app: playlist-recommender
  ports:
    - protocol: TCP
      port: 30502
      targetPort: 5000
  type: ClusterIP