apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: altinojunior
spec:
  selector:
    app: playlist-recommender
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30502